train: ../train/images
val: ../valid/images
test: ../test/images

nc: 55
names: ['h10', 'h2', 'h3', 'h4', 'h5', 'h6', 'h7', 'h8', 'h9', 'ha', 'hb', 'hh', 'hv', 'j', 'k10', 'k2', 'k3', 'k4', 'k5', 'k6', 'k7', 'k8', 'k9', 'ka', 'kb', 'kh', 'kv', 'pile-face-down', 'pile-face-up', 'r10', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'ra', 'rb', 'rh', 'rv', 's10', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 'sa', 'sb', 'sh', 'sv']

roboflow:
  workspace: 0lauk0
  project: playing-cards-muou8
  version: 10
  license: CC BY 4.0
  url: https://universe.roboflow.com/0lauk0/playing-cards-muou8/dataset/10